ktor:
  environment: asd
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/login"
  realm: "Access to 'hello"

storage:
  url: "jdbc:postgresql://localhost:5432/"  
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "root"
